apiVersion: v1
kind: Service
metadata:
  name: demo-gis-service
  labels:
    app: demo-gis
    tier: web
spec:
  type: LoadBalancer
  loadBalancerIP: "{{YOUR_STATIC_IP}}"
  ports:
  - name: gemo-gis-port
    protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: demo-gis
    tier: web